import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AuthProvider } from "@/components/user-profile-context";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NSCC - E-Sports Lounge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mulish.className} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {children}
          </AuthProvider>
          <Toaster duration={4000} richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
